"""add skill_level and elo_rating to users

Revision ID: 4d017e67c60c
Revises: 
Create Date: 2026-06-04 00:17:23.387194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d017e67c60c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('battle_rooms', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('battle_rooms', 'round_started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('battle_rooms', 'round_ends_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.add_column('app_users', sa.Column('skill_level', sa.String(), nullable=True))
    op.add_column('app_users', sa.Column('elo_rating', sa.Integer(), nullable=True))
    op.drop_constraint('app_users_telegram_chat_id_key', 'app_users', type_='unique')
    op.drop_constraint('app_users_telegram_username_key', 'app_users', type_='unique')
    op.drop_index('ix_app_users_telegram_chat_id', table_name='app_users')
    op.create_index(op.f('ix_app_users_telegram_chat_id'), 'app_users', ['telegram_chat_id'], unique=True)
    op.drop_index('ix_app_users_telegram_username', table_name='app_users')
    op.create_index(op.f('ix_app_users_telegram_username'), 'app_users', ['telegram_username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_users_telegram_username'), table_name='app_users')
    op.create_index('ix_app_users_telegram_username', 'app_users', ['telegram_username'], unique=False)
    op.drop_index(op.f('ix_app_users_telegram_chat_id'), table_name='app_users')
    op.create_index('ix_app_users_telegram_chat_id', 'app_users', ['telegram_chat_id'], unique=False)
    op.create_unique_constraint('app_users_telegram_username_key', 'app_users', ['telegram_username'])
    op.create_unique_constraint('app_users_telegram_chat_id_key', 'app_users', ['telegram_chat_id'])
    op.drop_column('app_users', 'elo_rating')
    op.drop_column('app_users', 'skill_level')
    op.alter_column('battle_rooms', 'round_ends_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('battle_rooms', 'round_started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('battle_rooms', 'started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
