"""remove theme_color from users

Revision ID: 5587636000d4
Revises: 4d017e67c60c
Create Date: 2026-06-04 15:19:16.303699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5587636000d4'
down_revision: Union[str, None] = '4d017e67c60c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_users', 'theme_color')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_users', sa.Column('theme_color', sa.VARCHAR(length=50), server_default=sa.text("'blue'::character varying"), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
