"""add views to club discussions

Revision ID: add_views_to_club_discussions
Revises: 
Create Date: 2026-06-29 12:35:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_views_to_club_discussions'
down_revision = 'simplify_elo_system_and_add_leaderboard'  # Update this to the latest migration
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club_discussions', sa.Column('views', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('club_discussions', 'views')
    # ### end Alembic commands ###
