"""simplify elo system and add leaderboard

Revision ID: simplify_elo_system
Revises: add_account_lockout
Create Date: 2026-06-18 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'simplify_elo_system'
down_revision = None
branch_labels = None
depends_on = ('5587636000d4', 'add_account_lockout')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove rank, skill_level, win_rate, total_battles from app_users
    op.drop_column('app_users', 'rank')
    op.drop_column('app_users', 'skill_level')
    op.drop_column('app_users', 'win_rate')
    op.drop_column('app_users', 'total_battles')
    
    # Change elo_rating default from 1200 to 400
    op.alter_column('app_users', 'elo_rating',
                    existing_type=sa.Integer(),
                    nullable=False,
                    server_default='400')
    
    # Remove score from arguments
    op.drop_column('arguments', 'score')
    
    # Create elo_history table
    op.create_table('elo_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('battle_room_id', sa.Integer(), nullable=True),
        sa.Column('old_elo', sa.Integer(), nullable=False),
        sa.Column('new_elo', sa.Integer(), nullable=False),
        sa.Column('elo_change', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['battle_room_id'], ['battle_rooms.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_elo_history_user_id'), 'elo_history', ['user_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop elo_history table
    op.drop_index(op.f('ix_elo_history_user_id'), table_name='elo_history')
    op.drop_table('elo_history')
    
    # Add back score to arguments
    op.add_column('arguments', sa.Column('score', sa.Integer(), nullable=True, server_default='0'))
    
    # Change elo_rating default back to 1200
    op.alter_column('app_users', 'elo_rating',
                    existing_type=sa.Integer(),
                    nullable=True,
                    server_default='1200')
    
    # Add back rank, skill_level, win_rate, total_battles to app_users
    op.add_column('app_users', sa.Column('total_battles', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('app_users', sa.Column('win_rate', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('app_users', sa.Column('skill_level', sa.String(), nullable=True, server_default='intermediate'))
    op.add_column('app_users', sa.Column('rank', sa.String(), nullable=True, server_default='Bronze'))
    
    # ### end Alembic commands ###
